### ISSUE TITLE
nupnpSearch() can not discover bridges

### ISSUE THREAD

**Issue by mstfldmr** [peter-murray/node-hue-api#102]
`nupnpSearch()` function can not discover bridges both using a promise and a callback:

```
// Using a promise
hue.nupnpSearch().then(displayBridges).done();

// Using a callback
hue.nupnpSearch(function(err, result) {
    if (err) throw err;
    displayBridges(result);
});

```
However, `upnpSearch()` function can discover them:

`hue.upnpSearch(timeout).then(displayBridges).done();`

My NodeJS version is: 4.4.0

```
# node --version
v4.4.0
```

**Comment by peter-murray** [comment]
Using node.js `4.4.7` the `upnpSearch()` function works for me. You have to have registered the bridge online before you can successfully call the function and get results, as this is just hitting the https://www.meethue.com/api/nupnp endpoint.
