### ISSUE TITLE
Engine error on install

### ISSUE THREAD

**Issue by simmo** [peter-murray/node-hue-api#104]
On installing the package via NPM/Yarn I get:
`warning node-hue-api@2.4.0: The engine "nodejs" appears to be invalid.`

My assumption is that it is the 'engine' block in the package.json.

I'm on a Mac so Node cli is `node` rather than `nodejs`. I can submit a PR to change to `node`? Unless its set to `nodejs` for a particular reason?

**Comment by peter-murray** [comment]
Thanks, fixed in release 2.4.1
