### ISSUE TITLE
Batch light commands?

### ISSUE THREAD

**Issue by sinedied** [peter-murray/node-hue-api#107]
Is there a way to send commands to all lights in one go, instead of one at a time? For example, to turn all lights on or off?

**Comment by isfett** [comment]
use group 0, as described.

**Comment by isfett** [comment]
> Please note, the Lightset 0 group, is a special instance and will always exist and have the id of "0" as specified in the Hue Api documentation. Due to this internal group being maintained by the bridge internally, it will not return an array of light ids like the other groups in the results returned from a call to groups().

> If you need to get the full details of the Lightset 0 groups, then you can obtain that by using the getGroup() function, using an id argument of 0.

https://github.com/peter-murray/node-hue-api#working-with-groups

**Comment by sinedied** [comment]
Oups, missed that, thanks! ;)
