### ISSUE TITLE
Transition times incorrect

### ISSUE THREAD

**Issue by TomMettam** [peter-murray/node-hue-api#109]
After a lot of swearing at my transitions apparently not working, I discovered that the transition durations are not working as documented.

Rather than being in milliseconds (i.e, 4000 = 4 seconds), to get a 4 second transition I had to specify 40.

**Comment by peter-murray** [comment]
What part of the API are you using? Are you passing in JSON, or a lightstate object, and to which function call.

**Comment by TomMettam** [comment]
`var lightState = hueBase.lightState;
var xy = $scope.toXY($scope.colours[$scope.sequences[entity].col]); //converts rgb to xy
var state = lightState.create().on().xy(xy).transitionTime(200).brightness(20);
api.setGroupLightState(group, state, function(err, lights) {
            if (err)
            {
                console.error(err);
            }
});`

**Comment by peter-murray** [comment]
Thanks, I see that I messed up the documentation. There was already a function there `transtion` that was working on actual milliseconds, but the documentation for `transitiontime` and `transtionTime` was wrong.

I also added two more convenience functions of `transitiontime_milliseconds` and `transitionTime_milliseconds` as shortcuts to `transition` to operate in millisecond values.
