### ISSUE TITLE
Node-Red Hue Set

### ISSUE THREAD

**Issue by lespatots** [peter-murray/node-hue-api#111]
I would like to drive the flow from a database but to do that I need to pass the Light ID into the SET node. I don't seem to be able to find how to do this. It seems I can pass anything else except that key data. Sorry if this is the wrong place to raise this!

**Comment by peter-murray** [comment]
This module has nothing to do with node red, you should raise an issue on the associated node red plugin/module that is using this module. This module is just a wrapper around the hue api, and you can specify the light id on all code that interacts with lights directly.
