### ISSUE TITLE
Change detections

### ISSUE THREAD

**Issue by ptorrent** [peter-murray/node-hue-api#115]
Hello !

I would like to know if it is possible to detect the changes of state of a lamp without making a loop of requests?

Something like api.on('state change' .... 

Is it possible ?

Thanks a lot for your reply !

**Comment by peter-murray** [comment]
Unfortunately that is not possible, the hue bridge has nothing to support that it is purely a request response over http. It has throttling and a maximum number of requests per second it can support, so if you do go that route of polling be careful you do not overload it.
