### ISSUE TITLE
meethue.com/api/nupnp deprecated (gone per July 1st)

### ISSUE THREAD

**Issue by hermanbanken** [peter-murray/node-hue-api#126]
> **Bridge Discovery Endpoint Change**
> Effective July 1 2018 (nupnp) bridge discovery is supported by a new endpoint, which is https://discovery.meethue.com. The old endpoint  www.meethue.com/api/nupnp has been deprecated but remains available until July 1 2019. We had to change to the new endpoint such that we can guarantee a high reliability with the increased amount of traffic we are getting. There are no other differences besides the url. If you experience issues, please let us know.

This repo needs to switch over, support will be dropped very soon.

**Comment by peter-murray** [comment]
Fixed in release v2.4.5
