### ISSUE TITLE
Entertainment API support

### ISSUE THREAD

**Issue by jacklj** [peter-murray/node-hue-api#128]
Hello, is it on your roadmap to support the Hue Entertainment API? 

Thanks so much for all your hard work!

Have a great day

**Comment by peter-murray** [comment]
Hi,

Yes it is, that will come in the 3.x release that is being worked on currently. I expect to start releasing the first versions of it in the next couple of weeks (there are some alpha versions already) and will be adding the newer features to those releases.

**Comment by jacklj** [comment]
That's great news, thanks!

**Comment by jacklj** [comment]
Are the alpha versions available to test?

**Comment by jacklj** [comment]
Ah found it https://github.com/peter-murray/node-hue-api/tree/v_3#3x

Thanks

**Comment by willyboy** [comment]
In case anyone else finds this issue and thinks streaming is supported, see @peter-murray's notes here https://github.com/peter-murray/node-hue-api/issues/163
