### ISSUE TITLE
Missing parameter for the username.

### ISSUE THREAD

**Issue by KnisterPeter** [peter-murray/node-hue-api#131]
According to the [api](https://github.com/peter-murray/node-hue-api/blob/master/lib/api/Remote.js#L26), this [line](https://github.com/peter-murray/node-hue-api/blob/master/lib/api/http/RemoteBootstrap.js#L42) should set undefined as the first parameter, because its the `remoteBridgeId`.

This leads to a user which could not be easily identified as the one created by the app, because it is named after the `node-hue-api`. This is hard to understand for users.

**Comment by peter-murray** [comment]
Thanks, will fix that tomorrow, it needs to default or expose a bridge Id there

**Comment by peter-murray** [comment]
Fix is published in npm registry as version `3.1.2`
