### ISSUE TITLE
Living Whites Plug not controlable with v3

### ISSUE THREAD

**Issue by foxriver76** [peter-murray/node-hue-api#141]
Like in our other conversation about Osram Smart Plugs one of my users is using an old Philips Living Whites Plug. 

With node-hue-api v2 he could control it. With v3 the error is: `Error: Unknown type, Dimmable plug-in unit`

If you need more information, please let me know.

**Comment by foxriver76** [comment]
```json
{"state":{"on":true,"bri":254,"alert":"select","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"Dimmable plug-in unit","name":"Weihnachten Terrassenfenster","modelid":"LWL001","manufacturername":"Philips","productname":"LivingWhites Plug","capabilities":{"certified":true,"control":{},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"plug","function":"functional","direction":"omnidirectional"},"uniqueid":"00:17:88:01:00:2f:80:b1-0c","swversion":"1.0.1.4591"}
```

**Comment by peter-murray** [comment]
Thanks, will sort that tomorrow for you.

This was one of the reasons I did not originally go with matching of types to instance objects... starting to regret the decision to match to types as there is no definitive list of types that are supported.

**Comment by peter-murray** [comment]
`3.3.2` is in the npm registry that should resolve this
