### ISSUE TITLE
Feature Request: RGB for setGroupLightState

### ISSUE THREAD

**Issue by lolaustin** [peter-murray/node-hue-api#145]
Currently only setLightState has RGB.

**Comment by peter-murray** [comment]
The reason for that is that the rgb value has to be converted for each type of colour gamut for each light.

If you were to try to do this on a group, then you have to retrieve all the lights in the group, perform the conversion of rgb to hsl on each light, and then set that on each light, not via the grouping, so would creating a staggered effect as the lights in the group change as the bridge gets the request.

The hue API itself does not support rgb directly and the library provides it for individual lights as it can do this calculation and set the state with minimal noticeable issues. This would not apply in a group.

If you desire this type of thing, then a scene may be more appropriate, as you can set the rgb values in advance, save the scene and then recall it later using the group state with the scene id.

**Comment by lolaustin** [comment]
Ah, okay. Thanks for the response.
