### ISSUE TITLE
Bug in operators/index.js

### ISSUE THREAD

**Issue by DenisPryt** [peter-murray/node-hue-api#159]
`, GreaterThan = new RuleConditionOperator('gt' ['>'])` missed a comma between arguments. 
It was a hard to find why operation.payload was a null :)

**Comment by peter-murray** [comment]
I have published an updated version of `4.0.3-alpha.1` to npm registry for you to verify the fix on. I will release this officially in an up coming patch.

**Comment by DenisPryt** [comment]
I checked. All works fine. Thanks.

**Comment by peter-murray** [comment]
Released in 4.0.3
