### ISSUE TITLE
Purpose of `enableStreaming` method

### ISSUE THREAD

**Issue by foxriver76** [peter-murray/node-hue-api#163]
Hey, whats actually the purpose of `enableStreaming` method. `disableStreaming` stops syncing the lights with the Hue Sync Box, but `enableStreaming` just produces an error `Unauthorized User` at https://github.com/peter-murray/node-hue-api/blob/57619b670bc99f95a4ed82c48501b98d248cd77d/lib/api/http/Transport.js#L69

It seems like enabling the stream is not supported by the original hue api and needs an additional api. See https://github.com/ebaauw/homebridge-hue/issues/552 any plans to support Hue Sync Box in this library?

**Comment by peter-murray** [comment]
When I originally added this it was around evaluating adding streaming support for entertainment zones.

You c

**Comment by peter-murray** [comment]
Not sure why the ticket was closed...

By the way, the unauthorised user is possibly coming from a user account that was not created with the client key when it was created. Try using a new user with that flag turned on. If not, let me know the full details of the error and I can look into it.

**Comment by peter-murray** [comment]
Incidentally, the bridge can only support one active stream at a time

**Comment by foxriver76** [comment]
Thanks for sharing your thoughts on this. I totally agree with you on this. Also, it seems like recreation of the credentials worked for the user.
Furthermore, `enableStreaming` seems to do something on the API, because Hue Sync Box App and Philips Hue App both show a message that someone else is currently streaming and after 5 seconds the message disappears again and the Entertainment group shows streaming as false again everywhere. But as you said there is probably some action from the streaming device required too.

**Comment by peter-murray** [comment]
Once the streaming is enabled, you have 10 seconds to establish a connection, including handshaking over an dtls connection with the bridge, which uses the client key.

Streaming, if a dtls connection is established and handshaking is successful, will remain open until nothing is received for 10 seconds, or disable rest endpoint is called.

**Comment by Roaders** [comment]
so just for my understanding, is it possible to enable and disable the streaming to the sync box using this library? I was thinking that I would have to implement this myself. If it's already done here great!

**Comment by peter-murray** [comment]
This library has the enable/disable part of the API exposed only, which is done over REST. Once that is active there is a second API the streaming API that uses dtls. Due to some users using this library in the web browser and the depth of messy stuff you have to get into to use the dtls stuff in Node.js nothing more has been done to extend support for that aspect.

Considering the issues of flashing lights, updates and concerns about health and safety I am extremely wary of doing anything in that area based on all the warnings that Signify have in the documentation.
