### ISSUE TITLE
Update for newer versions of the Hue API

### ISSUE THREAD

**Issue by ryandesign** [peter-murray/node-hue-api#20]
In places, the readme says things like:

> The creation of groups is not officially supported in the released Hue API from Phillips (version 1.0). 

[Groups are fully supported](http://www.developers.meethue.com/documentation/groups-api) in the current version of the Hue API. The documentation and/or the module should be updated accordingly.

**Comment by peter-murray** [comment]
Cheers, I will have to go through the API documentation and make sure I have all the old and new functionality supported around this.

Once I have got the interactions working correctly via the code I will update the README.

It will likely get done this weekend, and hopefully published provided I don't run into any issues.
