### ISSUE TITLE
TypeError: Cannot set property 'ca' of undefined

### ISSUE THREAD

**Issue by SGunner2014** [peter-murray/node-hue-api#203]
Getting the above error when trying to use nupnpSearch from discovery.

![Screenshot 2021-08-24 at 18 13 38](https://user-images.githubusercontent.com/9029154/130660810-540acee2-da3b-435b-a529-d129b0798492.png)

I'm using typescript, but this error stops me from using the search function at all.

**Comment by peter-murray** [comment]
What version of Node.js and the library are you using here? Do you have some sample code as to how you are using this to create the error so that I can reproduce and test?

**Comment by peter-murray** [comment]
I see your PR, thanks

**Comment by peter-murray** [comment]
I have fixed this in the typescript branch and released version `5.0.0-beta.8`. There was a test for this already and it was not failing locally for me under Node.js 16. Can you provide some context as to the environment you are using (Node.js or browser etc...) so I can work out why this was failing in this case the tests not catching it.

Thank you for reporting this.
