### ISSUE TITLE
mDNS Discovery

### ISSUE THREAD

**Issue by drewterry** [peter-murray/node-hue-api#221]
According to [Hue documentation](https://developers.meethue.com/develop/application-design-guidance/hue-bridge-discovery/#:~:text=NOTE%201%20%E2%80%93%20UPnP%20(or%20more%20specifically%20the%20UPnP%20subset%20Simple%20Service%20Discovery%20Protocol%20(SSDP))%20used%20to%20be%20available%20as%20another%20discovery%20method%20but%20has%20been%20deprecated%20in%20favor%20of%20mDNS%20and%20will%20be%20disabled%20in%20Q2%202022) uPNP discovery will be discontinued Q2 2022 (now).  Is there a way to do this with `node-hue-api`?

>NOTE 1 – UPnP (or more specifically the UPnP subset Simple Service Discovery Protocol (SSDP)) used to be available as another discovery method but has been deprecated in favor of mDNS and will be disabled in Q2 2022

**Comment by peter-murray** [comment]
The library has supported the SSDP discovery along with the newer remote API discovery endpoint once it became available. I suspect that they will be removing this functionality from the actual bridges, and I have not successfully testing this discovery method for some time now, instead favouring the discovery endpoint myself for a while.

The existing SSDP discovery was exposed under the `upnpSearch()` function and the newer discovery endpoint based one was `nupnpSearch()`

I will look into adding support for mDNS discovery and see what is needed in that space.

**Comment by peter-murray** [comment]
Just an update, I have added mDNS locally to the library, but really not getting reliable of fast results inside my network when using it in practice.  I will continue to work on this due to the problems with the rate limiting on the discovery endpoint as this is also impacting my test suites.

**Comment by peter-murray** [comment]
I have just released version `5.0.0-beta.14` to npm registry, it includes a new `discovery.mdnsSearch()`, which at long last appears to be reliable on my network, please check it out and report back any issues or problems.

**Comment by pindab0ter** [comment]
I tested it today and it works great! Thanks for the update!
