### ISSUE TITLE
UPnP

### ISSUE THREAD

**Issue by ryandesign** [peter-murray/node-hue-api#25]
I notice that the `locateBridges` function uses the meethue.com NUPnP service. Have you considered also using UPnP as shown in the [Hue developer documentation](http://www.developers.meethue.com/documentation/hue-bridge-discovery)? Their flowchart shows using UPnP, and if no results are returned, then use NUPnP. Alternately, they suggest running the UPnP and NUPnP queries simultaneously.

**Comment by peter-murray** [comment]
I already do support both, in fact the UPnP search was the first thing that I implemented in this library...

I have updated the documentation and the names of the search functions to match the type of search being performed, so in the up coming `0.2.7` release there will be two new functions `upnpSearch` and `nupnpSearch` which should clarify the type of lookup being performed (previously they were named `locateBridges` and `searchForBridges` which will be deprecated).

I think it is best to leave it to the developer to decide on whether or not to fully implement a parallel search on the network, or a fallback approach when looking for their bridges.

**Comment by ryandesign** [comment]
Oh sorry. I didn't look closely enough. I was also misled by the fact that in hue-api/commands/discovery.js you define and in hue-api/bridge-discovery.js you use a variable `upnpLookup` describing the NUPnP URL. Somehow I inferred that because you called this `upnpLookup` and not `nupnpLookup` that you didn't have a real UPnP lookup feature.

I agree with providing the app developer with the building blocks to make the experience they want.

**Comment by peter-murray** [comment]
Yeah, unfortunately I had already named the UPnP lookup as something else and when adding the quicker lookup using N-UPnP chose something that made sense at at time, but was no a great descriptive name.

The next version will clean this up and make it a lot clearer. I should be releasing that by the end of the weekend, I need to do some work on the groups first.
