### ISSUE TITLE
group 0 does return lights

### ISSUE THREAD

**Issue by ryandesign** [peter-murray/node-hue-api#27]
The readme says:

> The "Lightset 0" Group is a special instance and will always exist and have the id of "0" as specified in the Hue Api documentation. Due to this internal group being maintained by the bridge internally, it will not return an array of light ids like any of the other types of Groups.

However, on my hue bridge, when I issue a `GET` request for /api/newdeveloper/groups/0 in CLIP, the result does include the list of lights:

```
{
	"name": "Lightset 0",
	"lights": [
		"1",
		"2",
		"3"
	],
	"type": "LightGroup",
	"action": {
		"on": false,
		"bri": 150,
		"hue": 2049,
		"sat": 0,
		"effect": "none",
		"xy": [
			0.3804,
			0.3768
		],
		"ct": 248,
		"colormode": "xy"
	}
}
```

**Comment by peter-murray** [comment]
It was meant to be reference to the `groups` function result, as that result will be missing the full details of that specific group.

I will clean up the documentation.
