### ISSUE TITLE
Support for the scenes API

### ISSUE THREAD

**Issue by knsv** [peter-murray/node-hue-api#29]
First of all. Thanks for a great project! Great functionality that really made the work with implementing the hue lights into my home automation system quite fun!

Now I am trying to unleash the creativity of my family when it comes to setting the lights to nice colors and combinations. For that I would like to use the scenes API which is not yet supported by your API.

Instead of doing a my own wrapper I have tried to enhance your API, I am about to create a pull request with those changes.

Thanks again for your work with this!

**Comment by peter-murray** [comment]
Thank you for your contribution, it is greatly appreciated.

I am working on a refactoring of the lightState and am adding in the missing parts of the API that I have not covered yet. Scenes was something that I started on this week, so I will take a look at your pull request this weekend and work it into my other changes.

This will get rolled up into the 1.0.0 release, as the lightState changes required me to break the API a little to ensure that all the issues with it were properly resolved. I have also greatly expanded the testing around this module to ensure that it works much better than it did.

Ther version 1.0.0 work is happening on a branch `dev-1.0.0` so I will be putting the scenes code into that this weekend.

Thanks once again.

**Comment by knsv** [comment]
Glad to be able to assist! You decide on when and how to close this issue.

**Comment by peter-murray** [comment]
I am building out tests for this, and am hoping to complete this by next week.

**Comment by peter-murray** [comment]
This is now present in the `1.0.0` release. It has been published to the npm registry.

I had to remove the support for scene activation by name as it is impossible to determine the correct scene based on name (at least in the current firmware on my bridge).

I will keep any eye on the future releases of the firmware to see if anything changes in this area.

Hopefully you will be happy with the implementation in `1.0.0` and it gives you what you need. Please let me know if there is anything you feel is missing, or cannot do using what is implemented.

Thanks,
 - Peter
