### ISSUE TITLE
API error crash

### ISSUE THREAD

**Issue by aml25** [peter-murray/node-hue-api#33]
Hello,

Every now and then I get this error:
Api Error: parameter, xy, is not modifiable. Device is set to off.

I'm not sure what is causing it, as it seems to be random.  One thought is I'm calling the API too quickly, but if I do the calls quickly on purpose it doesn't always crash.

**Comment by aml25** [comment]
/my/path/to/my/repo/NODE/node_modules/node-hue-api/node_modules/q/q.js:126
                    throw e;
                          ^

**Comment by aml25** [comment]
The cause has been found...  If I call .off() on a light that is already off then it crashes.

**Comment by peter-murray** [comment]
Yes, it is a feature of the bridge that you cannot set some colour values if the light is in an off state. It kind of makes sense, but was something they added recently in the firmware updates.
