### ISSUE TITLE
api.setGroupLightState(0, lightState.create().off()

### ISSUE THREAD

**Issue by neophob** [peter-murray/node-hue-api#41]
If I run `api.setGroupLightState(0, lightState.create().off())`nothing happens - if I address a single light bulb it works `api.setLightState(1, lightState.create().on())`.

**Comment by peter-murray** [comment]
Which version of the library are you experiencing this issue with?

**Comment by peter-murray** [comment]
This is resolved in version `1.0.2`, which has been published to npm Registry now.

**Comment by neophob** [comment]
wow, that was quicj, thanks!
