### ISSUE TITLE
alert() does not work (nothing happens, api says true)

### ISSUE THREAD

**Issue by neophob** [peter-murray/node-hue-api#43]
using api v1.0.2, if I use `api.setLightState(1, lightState.create().alert());` or `return api.setGroupLightState(0, lightState.create().alert());`nothing happens.

*Edit*: However `lightState.create().longAlert()`does work!

**Comment by peter-murray** [comment]
The documentation in the README is wrong, it is still detailing the old way the the LightState object worked.

In the new LightState, `alert()` will map to the under lying Bridge API payload of `{"alert": "none"}` now.
