### ISSUE TITLE
created scene id is 'NaN'

### ISSUE THREAD

**Issue by wind-rider** [peter-murray/node-hue-api#45]
I'm using node-hue-api 1.0.3 and I have not set a custom scene id prefix.

When calling api.createScene, the resulting id is a NaN, whereas this should be a unique string.

Example result json:

{ lights: [ '4', '5', '6' ], id: 'NaN' }

I think the problem is in
``````
HueApi.prototype._getScenePrefix = function () {
    return this._getConfig().scene_prefix;
};
```````

I think it should be
``````
HueApi.prototype._getScenePrefix = function () {
    return this._getConfig().scenePrefix;
};
```````

**Comment by peter-murray** [comment]
Thanks, good find, my test coverage was not sufficient, I have now improved this.

**Comment by wind-rider** [comment]
thank you for the quick fix!
