### ISSUE TITLE
parseuri Version not found

### ISSUE THREAD

**Issue by marcgille** [peter-murray/node-hue-api#57]
It seems from package.js that >=1.2.3-2 <1.3.0 is required whereas npm only provides up to 0.4.

**Comment by peter-murray** [comment]
There are two parseUri libraries, npm is case sensitive... https://www.npmjs.com/package/parseUri

**Comment by marcgille** [comment]
Thanks for the swift response. There might still be an issue with that in my usage pattern, which is using it in an npm package X and in turn using X in a package Y. The installation of X into Y fails with

notarget No compatible version found: parseuri@'>=1.2.3-2 <1.3.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'node-hue-api'
npm ERR! notarget 

This is just to let you know. I will investigate whether the issue is somwhere on my side or npm itself. But may be you also have ideas.

**Comment by marcgille** [comment]
For completeness: This is an npm problem and has been discussed before (https://github.com/npm/npm/issues/7933). As suggested in that issues, npm shrinkwrap does the trick for the scenario I have reported - which is an A > B > C closure as described in the article.

Still an obligation for the owners of parseUri and parseuri to sort things out - in particular as parseuri is used by such a popular package as socketio.

**Comment by peter-murray** [comment]
Based on your findings I have removed the dependency on parseUri, as it is really no longer necessary, it was only used to work around an issue with `url.parse()` a long time back. 

The update is present in  93ca0b34fa9eb93ac42324828 and will part of the next release of the library, but I would like to include a few more bug fixes in the next release.

**Comment by peter-murray** [comment]
Thanks for your efforts in getting to the bottom of the issue :+1:

**Comment by peter-murray** [comment]
This is now available in release 1.2.0
