### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [peter-murray/node-hue-api#63]
Hi Peter,

I work for Philips Hue Developer Support.  In case you were not aware, in a few months time we will be changing the way usernames are created on the bridge (for security reasons).  Custom whitelist usernames will no longer be allowed and the bridge randomly generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

I had a quick look at your code and it looks like you are POSTng the "username" (index.js line 1124 in _setCreateUserOptions method).  This will start failing around February 2016 so it should be removed. Looking at your description on your project page (Registering without an existing Device ID/User ID section) it appears you already have the code to using the Bridge Randomly generated username,  so hopefully it should be a simple case of just removing the option to generate custom usernames.  Apologies for the inconvenience.

Thanks
Steve

**Comment by peter-murray** [comment]
Thanks for the heads up, I will arrange to switch over in the next release.

**Comment by SteveyO** [comment]
Great thanks. Please leave a comment on here when done, so I can check at my end.
Steve
