### ISSUE TITLE
Wrong upper range maxValue for brightness

### ISSUE THREAD

**Issue by mwittig** [peter-murray/node-hue-api#75]
node-hue-api defines the range for brightness as 0..255. However, my understanding of the  [hue Core Concepts](http://www.developers.meethue.com/documentation/core-concepts) is, that the range should be 0..254!

When node-hue-api is used along with the [Hue Emulator](http://steveyo.github.io/Hue-Emulator/), a brightness value of 255 causes the emulator ro apparently flips the value to 0 as the virtual bulbs turn black. That is probably a bug in the emulator as the Core Concepts document is suggesting the bridge will turn a value of 255 to 254. Well, I currently have no bridge to test with. May be you can tell me. Anyhow, I think using a value of 255 should be regarded as bug. At least, the internal use of brightness as part of the color functions rgb and hsl, for example,  should only use the  range of 0..254.

**Comment by mwittig** [comment]
I have tested my fix with my own test program and it works as expected If .bri(255) is called, the value will   be changed internally to 254 as specified in the Core Concepts.

**Comment by peter-murray** [comment]
A very old version of the API did accept and use 255 as the maximum value. It was an oddity, but what the bridge did at the time.

Thanks for the update in putting this right under the newer versions of the API.
