### ISSUE TITLE
ECONNRESET node-hue-api 2.0.1

### ISSUE THREAD

**Issue by Connor-Knabe** [peter-murray/node-hue-api#79]
Hi I'm running Node 4.0.0 and I seem to get this error when I make a call.  What is weird is that the lights still change colors this is just displayed from the .fail() promise. 

```

hueState = lightState.create().rgb(r,g,b);
    hueState.on();
    setLight(hueState);

function setLight(hueState){
    api.setLightState(1, hueState)
        .then()
        .fail(displayError)
        .done();
}
```

{ [Error: connect ECONNRESET 192.168.0.103:80]
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'connect',
  address: '192.168.0.103',
  port: 80 }

Any ideas? I know this has been a bug in the past but I'm puzzled at why it is happening.  Thanks!

**Comment by peter-murray** [comment]
The only way I can manage to reproduce this in my testing based off the information you have provided is  when I set the location of the bridge to an invalid IP address for the bridge...

Can you share with me what specific version of the node-hue-api you are using, I tested this against the latest 2.0.1 release.
Also what actual version of Node.js are you running, is it really 4.0.0? When I tested I was using 4.2.2.

Thanks

**Comment by Connor-Knabe** [comment]
@peter-murray this doesn't seem to be an issue anymore I cannot seem to recreate it. Closing.
