### ISSUE TITLE
Nothing but { state: 'pending' } from getFullState()

### ISSUE THREAD

**Issue by trymbill** [peter-murray/node-hue-api#84]
I've been using the HueApi for a few weeks now and for some reason I can't get the state of a light or the fullState. Running config() returns the correct bridge, ip, name, etc.

I'm running node-hue-api v2.2.0. Any clue what could be going on?

**Comment by trymbill** [comment]
Calling ```/api/[user-hash]/lights``` works, returns the lights state.

**Comment by peter-murray** [comment]
Could you please clarify what you are running an not getting the "fullState" from, i.e. the function that is missing the information?

The version `2.2.0` was just released yesterday which exposes the `state` and `action` configuration from `lights` and `groups` respectively.

**Comment by peter-murray** [comment]
Closing due to no further response
