### ISSUE TITLE
Sensors API support

### ISSUE THREAD

**Issue by PeteLawrence** [peter-murray/node-hue-api#89]
Hi, thanks for all your work so far.  

Have you got any plan to implement the part of the Hue API that deals with sensors/switches?

**Comment by peter-murray** [comment]
Yes, it is on my list, it is the rules based part of the API.

I am not likely going to get to it until later this year though, due to work commitments so if there is a particular part you need, let me know and I may be able to get something done when I have some spare time.

**Comment by PeteLawrence** [comment]
I'm looking at integrating it into a homebridge plugin, so that button presses of a Hue sensor can be used to trigger Homekit scenes.  The particular parts I'd need would be listing of all sensors that have been registered, and getting the state of those sensors - eg. 5.1 and 5.5 of http://www.developers.meethue.com/documentation/sensors-api.

Happy to have a go at implementing it myself and raising a PR.

**Comment by peter-murray** [comment]
I have merged in an initial pull request on this that provides a `sensors` and `getSensors` function to list all the known sensors.

I need to expand the implementation to support the other API functions that you need. If you still want this, let me know exactly what API calls you need and I can prioritise those implementations for you.

Thanks

**Comment by Connor-Knabe** [comment]
@peter-murray I would love to see support for motion sensors (similar to what the native hue app does) so we could detect when motion is sensed and turn on lights accordingly (with more customization).

**Comment by bwired-nl** [comment]
any update on this, hope it will be supported

**Comment by peter-murray** [comment]
I will be adding more support in the next major release that I have started work on, but this incorporates a number of changes to remove be some older libraries and migrate to native promises, which will take some time to complete.

I would hope that I can get it finished before the end of the year.

**Comment by bwired-nl** [comment]
great! thanks for all the good work

**Comment by Baenker** [comment]
any news? Hope for motion sensor

**Comment by bwired-nl** [comment]
same here, please please update :-)

**Comment by bwired-nl** [comment]
HI Peter any update, i hope you find the time, this is best Hue nodejs code, but missing sensors etc. I dont want to switch :-(

**Comment by peter-murray** [comment]
Hi, I made a massive start on this over the festive period, https://github.com/peter-murray/node-hue-api/tree/v_3 but still need to finish off a couple of backward compatible pieces to ensure that you do not need to change too much code.

**Comment by bwired-nl** [comment]
Thanks Peter, we appreciate this very much!

**Comment by jaruba** [comment]
ping

**Comment by peter-murray** [comment]
I am just completing out the test suite for backwards compatibility and the documentation for the new API and the changes in the old/current API due to the removal of the ancient dependencies. There are still a few quirks that I am working through so as not to break too much of the existing code out there.

I expect to cut a release later this month.

**Comment by jaruba** [comment]
i got bored waiting and hooked into the hue sensor http api directly after about 30 mins after pinging

**Comment by peter-murray** [comment]
There is an `alpha` release `3.0.0-alpha.2` in the npm registry as of now, this will be released as the next major version once I complete the documentation. All the API functionality is practically locked down now for
* lights
* groups
* users
* configuration
* sensors

**Comment by peter-murray** [comment]
`3.0.0` was released to npm registry today there is support for sensors under the v3 api
