### ISSUE TITLE
maintenance status

### ISSUE THREAD

**Issue by pixelass** [peter-murray/node-hue-api#96]
Hi I just wanted to thank for this awesome api. 

I was wondering if you are actively maintaining this repo. I am thinking about writing a new version but wanted to check if it made sense to contribute to this one instead.

**Comment by peter-murray** [comment]
I have not made any changes recently, was waiting on the latest updates from Phillips to decide on what changes need to happen to support changes and new features they will be adding (like the new motion sensors).

I am on the fence currently, as the amount of reworking that needs to happen to bring it more into line with changes to javascript/Node.js with respect to language. It is not a trivial undertaking to pull out Q promises, replacing them with the native implementations (dropping callbacks in the process).

I am also very busy with work commitments recently and will not get the opportunity to do this reworking until mid to late November at the earliest.

So to answer your questions, yes I have an interest in maintaining this library, but it needs a bit of a refresh to bring it into line with current up to date Node.js/Javascript, which I will be doing later this year.

**Comment by pixelass** [comment]
That sounds like great news. I am pretty busy myself until November but I'd love to help where I can. 

I guess I will start from scratch and c&p some of the logic from here. Hopefully you can use my code when you decide to refactor this repo.
Not making promises though, since I'm not sure how much work this actually is.

**Comment by sqmk** [comment]
@pixelass Shameless plug, but I'm pretty active in development in this library, which has near 100% support for all of Philips Hue's API: https://github.com/sqmk/huejay
